//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 07:14:54 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ogf.org/nml/2013/05/base#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ogf.schemas.nml._2013._05.base;
